language: C

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gfortran liblapack3gf

script:
  - ./autogen.sh
  - ./configure FC=gfortran CC=gfortran LIBS="-l:liblapack.so.3gf -l:libblas.so.3gf"
  - make
  - make test
