language: C

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gfortran liblapack3gf hdf5-tools libhdf5-serial-dev

env:
  - COMPONENT=FreeON
  - COMPONENT=SCFeqs
  - COMPONENT=OneE
  - COMPONENT=QCTC
  - COMPONENT=HiCu

script: ./travis/build-freeon.sh $COMPONENT
