language: C

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gfortran liblapack3gf hdf5-tools libhdf5-serial-dev

env:
  - COMPONENT=Modules
  - COMPONENT=FreeON

script: ./travis/build-freeon.sh $COMPONENT
