gems:
  - jekyll-mentions

footer-links:
  github: nicolasbock

baseurl: "/freeon"

pages_list:
  Main: "/freeon"
  History: "History.html"
  Vision: "Vision.html"
  Users: "Users_Guide.html"
  Developers: "Developers_Guide.html"
  Collaboratory: "Collaboratory.html"
  Solvers: "Solvers.html"
  Publications: "Publications.html"
  Citing: "Citing_FreeON.html"
  Authors: "Authors.html"
  "An Introduction to QC": "An_introduction_to_Computational_Quantum_Chemistry_for_Biologists.html"
