#================================================================================
#
#     Matt Challacombe
#     Los Alamos National Laboratory
#     Copyright 2000, The University of California
#
#================================================================================
include $(MONDO_HOME)/Includes/RemoveAll
#
all:	
	math<CTraX.m
#
clean:
	rm -f $(REMOVEALL)
	rm -f \#*
	rm -f *~
