SUBROUTINE PutSubBlk(I,N,A1,A2,B1,B2,RS,CS,A,B)
  USE DerivedTypes
  USE GlobalScalars
  USE PrettyPrint
  IMPLICIT NONE
  INTEGER,INTENT(IN)         :: I,N,A1,A2,B1,B2,RS,CS
  REAL(DOUBLE),INTENT(INOUT) :: A(A1,A2)
  REAL(DOUBLE),INTENT(IN)    :: B(N,B1,B2)
  INTEGER                    :: IC,IR,RS1,CS1

  RS1=RS-1
  CS1=CS-1
  DO IC=1,B2
    DO IR=1,B1
      A(IR+RS1,IC+CS1)=A(IR+RS1,IC+CS1)+B(I,IR,IC)
    END DO 
  END DO

END SUBROUTINE PutSubBlk

