SUBROUTINE Int2221(N,IntCode,CBra,CKet,DisBufB,PrmBufB,DB,IB,SB,C,U)
 USE DerivedTypes
 USE GlobalScalars
 USE PrettyPrint
 USE InvExp
 INCLUDE "Int2221.Inc"
 REAL(DOUBLE)  :: Cx,Cy,Cz
 REAL(DOUBLE)  :: Zeta,Up,Px,Py,Pz,cp1,cp2,cp3
 REAL(DOUBLE)  :: Eta, Uq,Qx,Qy,Qz,cq1,cq2,cq3
 REAL(DOUBLE)  :: EtaQx,EtaQy,EtaQz
 REAL(DOUBLE)  :: r1xZpE,ZpE,Rkk,r1xZ,r1x2Z,rpxZ
 REAL(DOUBLE)  :: PAx,PAy,PAz,PQx,PQy,PQz
 REAL(DOUBLE)  :: QBx,QBy,QBz,WQx,WQy,WQz
 REAL(DOUBLE)  :: Wx,Wy,Wz,WPx,WPy,WPz
 REAL(DOUBLE)  :: T1,T2,T3,T4,TwoT
 REAL(DOUBLE)  :: R1,R2,R3,R4,R5,R6,R7,R8,R9
 REAL(DOUBLE)  :: G0,G1,G2,G3,G4,G5,G6,G7,G8,ET
 REAL(DOUBLE)  :: Ts0,Ts1,r1xE,r1x2E,rpxE,r1x2ZE
 INTEGER       :: I,J,K,ME,MG,l
 INTEGER       :: I0,I1,I2
 IF(N.EQ.0) RETURN
 C=0.0D0
 Cx=DisBufB( 8)
 Cy=DisBufB( 9)
 Cz=DisBufB(10)
 IF(IntCode.EQ. 2020201) THEN
 DO I=1,N
 I0 = SB%SLPrm%I(I)
 I2 = SB%SLDis%I(I)-4
 DO J=1,CKet
 I1=I0+(J-1)*DB%MAXP
 Eta = DB%PrmBuf%D(I1)
 Qx  = DB%PrmBuf%D(I1+1)
 Qy  = DB%PrmBuf%D(I1+2)
 Qz  = DB%PrmBuf%D(I1+3)
 Uq  = DB%PrmBuf%D(I1+4)
 cq1 = DB%PrmBuf%D(I1+5)
 cq2 = DB%PrmBuf%D(I1+6)
 cq3 = DB%PrmBuf%D(I1+7)
 r1xE  = 1.0D0/Eta
 r1x2E = 0.5D0*r1xE
 EtaQx = Eta*Qx
 EtaQy = Eta*Qy
 EtaQz = Eta*Qz
 QBx = Qx-DB%DisBuf%D(I2+7)
 QBy = Qy-DB%DisBuf%D(I2+8)
 QBz = Qz-DB%DisBuf%D(I2+9)
 DO K=1,CBra
 Zeta = PrmBufB(1,K)
 Px   = PrmBufB(2,K)
 Py   = PrmBufB(3,K)
 Pz   = PrmBufB(4,K)
 Up   = PrmBufB(5,K)
 cp1  = PrmBufB(6,K)
 cp2  = PrmBufB(7,K)
 cp3  = PrmBufB(8,K)
 ZpE  = Zeta+Eta
 r1xZpE = 1.0D0/ZpE
 r1x2ZE = 0.5D0*r1xZpE
 r1xZ   = 1.0D0/Zeta
 r1x2Z  = 0.5D0*r1xZ
 rpxZ   = Eta*r1xZpE
 rpxE   = Zeta*r1xZpE
 Rkk  = Up*Uq*DSQRT(r1xZpE)
 PAx = Px-Cx
 PAy = Py-Cy
 PAz = Pz-Cz
 Wx  = (Zeta*Px+EtaQx)*r1xZpE
 Wy  = (Zeta*Py+EtaQy)*r1xZpE
 Wz  = (Zeta*Pz+EtaQz)*r1xZpE
 WPx = Wx-Px
 WPy = Wy-Py
 WPz = Wz-Pz
 WQx = Wx - Qx
 WQy = Wy - Qy
 WQz = Wz - Qz
 PQx = Px - Qx
 PQy = Py - Qy
 PQz = Pz - Qz
 T1=(PQx*PQx+PQy*PQy+PQz*PQz)*Zeta*Eta*r1xZpE
 INCLUDE "RGen3.Inc"
 U(1)=R1                                                          
 U(6)=R2                                                          
 U(5)=R3                                                          
 U(2)=R4                                                          
 U(18)=QBx*U(1)+WQx*U(6)                                          
 U(35)=QBy*U(1)+WQy*U(6)                                          
 U(52)=QBz*U(1)+WQz*U(6)                                          
 U(8)=QBx*U(6)+WQx*U(5)                                           
 U(9)=QBy*U(6)+WQy*U(5)                                           
 U(11)=QBz*U(6)+WQz*U(5)                                          
 U(7)=QBx*U(5)+WQx*U(2)                                           
 U(10)=QBy*U(5)+WQy*U(2)                                          
 U(12)=QBz*U(5)+WQz*U(2)                                          
 U(2)=PAx*U(1)+WPx*U(6)                                           
 U(3)=PAy*U(1)+WPy*U(6)                                           
 U(4)=PAz*U(1)+WPz*U(6)                                           
 U(13)=PAx*U(6)+WPx*U(5)                                          
 U(14)=PAy*U(6)+WPy*U(5)                                          
 U(15)=PAz*U(6)+WPz*U(5)                                          
 U(19)=PAx*U(18)+WPx*U(8)+r1x2ZE*U(6)                                                      
 U(20)=PAy*U(18)+WPy*U(8)                                         
 U(21)=PAz*U(18)+WPz*U(8)                                         
 U(36)=PAx*U(35)+WPx*U(9)                                         
 U(37)=PAy*U(35)+WPy*U(9)+r1x2ZE*U(6)                                                      
 U(38)=PAz*U(35)+WPz*U(9)                                         
 U(53)=PAx*U(52)+WPx*U(11)                                        
 U(54)=PAy*U(52)+WPy*U(11)                                        
 U(55)=PAz*U(52)+WPz*U(11)+r1x2ZE*U(6)                                                     
 U(16)=PAx*U(8)+WPx*U(7)+r1x2ZE*U(5)                                                       
 U(17)=PAy*U(8)+WPy*U(7)                                          
 U(26)=PAz*U(8)+WPz*U(7)                                          
 U(28)=PAx*U(9)+WPx*U(10)                                         
 U(29)=PAy*U(9)+WPy*U(10)+r1x2ZE*U(5)                                                      
 U(30)=PAz*U(9)+WPz*U(10)                                         
 U(31)=PAx*U(11)+WPx*U(12)                                        
 U(32)=PAy*U(11)+WPy*U(12)                                        
 U(33)=PAz*U(11)+WPz*U(12)+r1x2ZE*U(5)                                                     
 U(22)=PAx*U(19)+WPx*U(16)+r1x2Z*(U(18)-rpxZ*U(8))+r1x2ZE*U(13)                            
 U(23)=PAx*U(20)+WPx*U(17)+r1x2ZE*U(14)                                                    
 U(25)=PAx*U(21)+WPx*U(26)+r1x2ZE*U(15)                                                    
 U(41)=PAy*U(37)+WPy*U(29)+r1x2Z*(U(35)-rpxZ*U(9))+r1x2ZE*U(14)                            
 U(43)=PAy*U(38)+WPy*U(30)+r1x2ZE*U(15)                                                    
 U(61)=PAz*U(55)+WPz*U(33)+r1x2Z*(U(52)-rpxZ*U(11))+r1x2ZE*U(15)                           
 U(5)=PAx*U(2)+WPx*U(13)+r1x2Z*(U(1)-rpxZ*U(6))                                            
 U(7)=PAy*U(3)+WPy*U(14)+r1x2Z*(U(1)-rpxZ*U(6))                                            
 U(10)=PAz*U(4)+WPz*U(15)+r1x2Z*(U(1)-rpxZ*U(6))                                           
 U(24)=PAy*U(20)+WPy*U(17)+r1x2Z*(U(18)-rpxZ*U(8))                                         
 U(27)=PAz*U(21)+WPz*U(26)+r1x2Z*(U(18)-rpxZ*U(8))                                         
 U(39)=PAx*U(36)+WPx*U(28)+r1x2Z*(U(35)-rpxZ*U(9))                                         
 U(44)=PAz*U(38)+WPz*U(30)+r1x2Z*(U(35)-rpxZ*U(9))                                         
 U(56)=PAx*U(53)+WPx*U(31)+r1x2Z*(U(52)-rpxZ*U(11))                                        
 U(58)=PAy*U(54)+WPy*U(32)+r1x2Z*(U(52)-rpxZ*U(11))                                        
 U(6)=PAx*U(3)+WPx*U(14)                                          
 U(8)=PAx*U(4)+WPx*U(15)                                          
 U(9)=PAy*U(4)+WPy*U(15)                                          
 U(26)=PAy*U(21)+WPy*U(26)                                        
 U(40)=PAx*U(37)+WPx*U(29)                                        
 U(42)=PAx*U(38)+WPx*U(30)                                        
 U(57)=PAx*U(54)+WPx*U(32)                                        
 U(59)=PAx*U(55)+WPx*U(33)                                        
 U(60)=PAy*U(55)+WPy*U(33)                                        
 C(I,1)=C(I,1)+U(1)*cp1*cq1                                       
 C(I,2)=C(I,2)+U(2)*cp3*cq1                                       
 C(I,3)=C(I,3)+U(3)*cp3*cq1                                       
 C(I,4)=C(I,4)+U(4)*cp3*cq1                                       
 C(I,5)=C(I,5)+U(2)*cp2*cq1                                       
 C(I,6)=C(I,6)+U(5)*cq1                                           
 C(I,7)=C(I,7)+U(1)*cp3*cq1                                       
 C(I,8)=C(I,8)+U(2)*cq1                                           
 C(I,9)=C(I,9)+U(3)*cp2*cq1                                       
 C(I,10)=C(I,10)+U(6)*cq1                                         
 C(I,11)=C(I,11)+U(7)*cq1                                         
 C(I,12)=C(I,12)+U(3)*cq1                                         
 C(I,13)=C(I,13)+U(4)*cp2*cq1                                     
 C(I,14)=C(I,14)+U(8)*cq1                                         
 C(I,15)=C(I,15)+U(9)*cq1                                         
 C(I,16)=C(I,16)+U(10)*cq1                                        
 C(I,17)=C(I,17)+U(4)*cq1                                         
 C(I,18)=C(I,18)+U(18)*cp1                                        
 C(I,19)=C(I,19)+U(19)*cp3                                        
 C(I,20)=C(I,20)+U(20)*cp3                                        
 C(I,21)=C(I,21)+U(21)*cp3                                        
 C(I,22)=C(I,22)+U(19)*cp2                                        
 C(I,23)=C(I,23)+U(22)                                            
 C(I,24)=C(I,24)+U(18)*cp3                                        
 C(I,25)=C(I,25)+U(19)                                            
 C(I,26)=C(I,26)+U(20)*cp2                                        
 C(I,27)=C(I,27)+U(23)                                            
 C(I,28)=C(I,28)+U(24)                                            
 C(I,29)=C(I,29)+U(20)                                            
 C(I,30)=C(I,30)+U(21)*cp2                                        
 C(I,31)=C(I,31)+U(25)                                            
 C(I,32)=C(I,32)+U(26)                                            
 C(I,33)=C(I,33)+U(27)                                            
 C(I,34)=C(I,34)+U(21)                                            
 C(I,35)=C(I,35)+U(35)*cp1                                        
 C(I,36)=C(I,36)+U(36)*cp3                                        
 C(I,37)=C(I,37)+U(37)*cp3                                        
 C(I,38)=C(I,38)+U(38)*cp3                                        
 C(I,39)=C(I,39)+U(36)*cp2                                        
 C(I,40)=C(I,40)+U(39)                                            
 C(I,41)=C(I,41)+U(35)*cp3                                        
 C(I,42)=C(I,42)+U(36)                                            
 C(I,43)=C(I,43)+U(37)*cp2                                        
 C(I,44)=C(I,44)+U(40)                                            
 C(I,45)=C(I,45)+U(41)                                            
 C(I,46)=C(I,46)+U(37)                                            
 C(I,47)=C(I,47)+U(38)*cp2                                        
 C(I,48)=C(I,48)+U(42)                                            
 C(I,49)=C(I,49)+U(43)                                            
 C(I,50)=C(I,50)+U(44)                                            
 C(I,51)=C(I,51)+U(38)                                            
 C(I,52)=C(I,52)+U(52)*cp1                                        
 C(I,53)=C(I,53)+U(53)*cp3                                        
 C(I,54)=C(I,54)+U(54)*cp3                                        
 C(I,55)=C(I,55)+U(55)*cp3                                        
 C(I,56)=C(I,56)+U(53)*cp2                                        
 C(I,57)=C(I,57)+U(56)                                            
 C(I,58)=C(I,58)+U(52)*cp3                                        
 C(I,59)=C(I,59)+U(53)                                            
 C(I,60)=C(I,60)+U(54)*cp2                                        
 C(I,61)=C(I,61)+U(57)                                            
 C(I,62)=C(I,62)+U(58)                                            
 C(I,63)=C(I,63)+U(54)                                            
 C(I,64)=C(I,64)+U(55)*cp2                                        
 C(I,65)=C(I,65)+U(59)                                            
 C(I,66)=C(I,66)+U(60)                                            
 C(I,67)=C(I,67)+U(61)                                            
 C(I,68)=C(I,68)+U(55)                                            
 ENDDO
 ENDDO
 ENDDO
 ELSEIF(IntCode.EQ. 2020301) THEN
 DO I=1,N
 I0 = SB%SLPrm%I(I)
 I2 = SB%SLDis%I(I)-4
 DO J=1,CKet
 I1=I0+(J-1)*DB%MAXP
 Eta = DB%PrmBuf%D(I1)
 Qx  = DB%PrmBuf%D(I1+1)
 Qy  = DB%PrmBuf%D(I1+2)
 Qz  = DB%PrmBuf%D(I1+3)
 Uq  = DB%PrmBuf%D(I1+4)
 cq1 = DB%PrmBuf%D(I1+5)
 cq2 = DB%PrmBuf%D(I1+6)
 cq3 = DB%PrmBuf%D(I1+7)
 r1xE  = 1.0D0/Eta
 r1x2E = 0.5D0*r1xE
 EtaQx = Eta*Qx
 EtaQy = Eta*Qy
 EtaQz = Eta*Qz
 QBx = Qx-DB%DisBuf%D(I2+7)
 QBy = Qy-DB%DisBuf%D(I2+8)
 QBz = Qz-DB%DisBuf%D(I2+9)
 DO K=1,CBra
 Zeta = PrmBufB(1,K)
 Px   = PrmBufB(2,K)
 Py   = PrmBufB(3,K)
 Pz   = PrmBufB(4,K)
 Up   = PrmBufB(5,K)
 cp1  = PrmBufB(6,K)
 cp2  = PrmBufB(7,K)
 cp3  = PrmBufB(8,K)
 ZpE  = Zeta+Eta
 r1xZpE = 1.0D0/ZpE
 r1x2ZE = 0.5D0*r1xZpE
 r1xZ   = 1.0D0/Zeta
 r1x2Z  = 0.5D0*r1xZ
 rpxZ   = Eta*r1xZpE
 rpxE   = Zeta*r1xZpE
 Rkk  = Up*Uq*DSQRT(r1xZpE)
 PAx = Px-Cx
 PAy = Py-Cy
 PAz = Pz-Cz
 Wx  = (Zeta*Px+EtaQx)*r1xZpE
 Wy  = (Zeta*Py+EtaQy)*r1xZpE
 Wz  = (Zeta*Pz+EtaQz)*r1xZpE
 WPx = Wx-Px
 WPy = Wy-Py
 WPz = Wz-Pz
 WQx = Wx - Qx
 WQy = Wy - Qy
 WQz = Wz - Qz
 PQx = Px - Qx
 PQy = Py - Qy
 PQz = Pz - Qz
 T1=(PQx*PQx+PQy*PQy+PQz*PQz)*Zeta*Eta*r1xZpE
 INCLUDE "RGen3.Inc"
 U(1)=R1                                                          
 U(6)=R2                                                          
 U(5)=R3                                                          
 U(2)=R4                                                          
 U(18)=QBx*U(1)+WQx*U(6)                                          
 U(35)=QBy*U(1)+WQy*U(6)                                          
 U(52)=QBz*U(1)+WQz*U(6)                                          
 U(8)=QBx*U(6)+WQx*U(5)                                           
 U(9)=QBy*U(6)+WQy*U(5)                                           
 U(11)=QBz*U(6)+WQz*U(5)                                          
 U(7)=QBx*U(5)+WQx*U(2)                                           
 U(10)=QBy*U(5)+WQy*U(2)                                          
 U(12)=QBz*U(5)+WQz*U(2)                                          
 U(2)=PAx*U(1)+WPx*U(6)                                           
 U(3)=PAy*U(1)+WPy*U(6)                                           
 U(4)=PAz*U(1)+WPz*U(6)                                           
 U(13)=PAx*U(6)+WPx*U(5)                                          
 U(14)=PAy*U(6)+WPy*U(5)                                          
 U(15)=PAz*U(6)+WPz*U(5)                                          
 U(19)=PAx*U(18)+WPx*U(8)+r1x2ZE*U(6)                                                      
 U(20)=PAy*U(18)+WPy*U(8)                                         
 U(21)=PAz*U(18)+WPz*U(8)                                         
 U(36)=PAx*U(35)+WPx*U(9)                                         
 U(37)=PAy*U(35)+WPy*U(9)+r1x2ZE*U(6)                                                      
 U(38)=PAz*U(35)+WPz*U(9)                                         
 U(53)=PAx*U(52)+WPx*U(11)                                        
 U(54)=PAy*U(52)+WPy*U(11)                                        
 U(55)=PAz*U(52)+WPz*U(11)+r1x2ZE*U(6)                                                     
 U(16)=PAx*U(8)+WPx*U(7)+r1x2ZE*U(5)                                                       
 U(17)=PAy*U(8)+WPy*U(7)                                          
 U(26)=PAz*U(8)+WPz*U(7)                                          
 U(28)=PAx*U(9)+WPx*U(10)                                         
 U(29)=PAy*U(9)+WPy*U(10)+r1x2ZE*U(5)                                                      
 U(30)=PAz*U(9)+WPz*U(10)                                         
 U(31)=PAx*U(11)+WPx*U(12)                                        
 U(32)=PAy*U(11)+WPy*U(12)                                        
 U(33)=PAz*U(11)+WPz*U(12)+r1x2ZE*U(5)                                                     
 U(22)=PAx*U(19)+WPx*U(16)+r1x2Z*(U(18)-rpxZ*U(8))+r1x2ZE*U(13)                            
 U(23)=PAx*U(20)+WPx*U(17)+r1x2ZE*U(14)                                                    
 U(25)=PAx*U(21)+WPx*U(26)+r1x2ZE*U(15)                                                    
 U(41)=PAy*U(37)+WPy*U(29)+r1x2Z*(U(35)-rpxZ*U(9))+r1x2ZE*U(14)                            
 U(43)=PAy*U(38)+WPy*U(30)+r1x2ZE*U(15)                                                    
 U(61)=PAz*U(55)+WPz*U(33)+r1x2Z*(U(52)-rpxZ*U(11))+r1x2ZE*U(15)                           
 U(5)=PAx*U(2)+WPx*U(13)+r1x2Z*(U(1)-rpxZ*U(6))                                            
 U(7)=PAy*U(3)+WPy*U(14)+r1x2Z*(U(1)-rpxZ*U(6))                                            
 U(10)=PAz*U(4)+WPz*U(15)+r1x2Z*(U(1)-rpxZ*U(6))                                           
 U(24)=PAy*U(20)+WPy*U(17)+r1x2Z*(U(18)-rpxZ*U(8))                                         
 U(27)=PAz*U(21)+WPz*U(26)+r1x2Z*(U(18)-rpxZ*U(8))                                         
 U(39)=PAx*U(36)+WPx*U(28)+r1x2Z*(U(35)-rpxZ*U(9))                                         
 U(44)=PAz*U(38)+WPz*U(30)+r1x2Z*(U(35)-rpxZ*U(9))                                         
 U(56)=PAx*U(53)+WPx*U(31)+r1x2Z*(U(52)-rpxZ*U(11))                                        
 U(58)=PAy*U(54)+WPy*U(32)+r1x2Z*(U(52)-rpxZ*U(11))                                        
 U(6)=PAx*U(3)+WPx*U(14)                                          
 U(8)=PAx*U(4)+WPx*U(15)                                          
 U(9)=PAy*U(4)+WPy*U(15)                                          
 U(26)=PAy*U(21)+WPy*U(26)                                        
 U(40)=PAx*U(37)+WPx*U(29)                                        
 U(42)=PAx*U(38)+WPx*U(30)                                        
 U(57)=PAx*U(54)+WPx*U(32)                                        
 U(59)=PAx*U(55)+WPx*U(33)                                        
 U(60)=PAy*U(55)+WPy*U(33)                                        
 C(I,1)=C(I,1)+U(18)*cp1                                          
 C(I,2)=C(I,2)+U(19)*cp3                                          
 C(I,3)=C(I,3)+U(20)*cp3                                          
 C(I,4)=C(I,4)+U(21)*cp3                                          
 C(I,5)=C(I,5)+U(19)*cp2                                          
 C(I,6)=C(I,6)+U(22)                                              
 C(I,7)=C(I,7)+U(18)*cp3                                          
 C(I,8)=C(I,8)+U(19)                                              
 C(I,9)=C(I,9)+U(20)*cp2                                          
 C(I,10)=C(I,10)+U(23)                                            
 C(I,11)=C(I,11)+U(24)                                            
 C(I,12)=C(I,12)+U(20)                                            
 C(I,13)=C(I,13)+U(21)*cp2                                        
 C(I,14)=C(I,14)+U(25)                                            
 C(I,15)=C(I,15)+U(26)                                            
 C(I,16)=C(I,16)+U(27)                                            
 C(I,17)=C(I,17)+U(21)                                            
 C(I,18)=C(I,18)+U(35)*cp1                                        
 C(I,19)=C(I,19)+U(36)*cp3                                        
 C(I,20)=C(I,20)+U(37)*cp3                                        
 C(I,21)=C(I,21)+U(38)*cp3                                        
 C(I,22)=C(I,22)+U(36)*cp2                                        
 C(I,23)=C(I,23)+U(39)                                            
 C(I,24)=C(I,24)+U(35)*cp3                                        
 C(I,25)=C(I,25)+U(36)                                            
 C(I,26)=C(I,26)+U(37)*cp2                                        
 C(I,27)=C(I,27)+U(40)                                            
 C(I,28)=C(I,28)+U(41)                                            
 C(I,29)=C(I,29)+U(37)                                            
 C(I,30)=C(I,30)+U(38)*cp2                                        
 C(I,31)=C(I,31)+U(42)                                            
 C(I,32)=C(I,32)+U(43)                                            
 C(I,33)=C(I,33)+U(44)                                            
 C(I,34)=C(I,34)+U(38)                                            
 C(I,35)=C(I,35)+U(52)*cp1                                        
 C(I,36)=C(I,36)+U(53)*cp3                                        
 C(I,37)=C(I,37)+U(54)*cp3                                        
 C(I,38)=C(I,38)+U(55)*cp3                                        
 C(I,39)=C(I,39)+U(53)*cp2                                        
 C(I,40)=C(I,40)+U(56)                                            
 C(I,41)=C(I,41)+U(52)*cp3                                        
 C(I,42)=C(I,42)+U(53)                                            
 C(I,43)=C(I,43)+U(54)*cp2                                        
 C(I,44)=C(I,44)+U(57)                                            
 C(I,45)=C(I,45)+U(58)                                            
 C(I,46)=C(I,46)+U(54)                                            
 C(I,47)=C(I,47)+U(55)*cp2                                        
 C(I,48)=C(I,48)+U(59)                                            
 C(I,49)=C(I,49)+U(60)                                            
 C(I,50)=C(I,50)+U(61)                                            
 C(I,51)=C(I,51)+U(55)                                            
 ENDDO
 ENDDO
 ENDDO
 ELSEIF(IntCode.EQ. 3020201) THEN
 DO I=1,N
 I0 = SB%SLPrm%I(I)
 I2 = SB%SLDis%I(I)-4
 DO J=1,CKet
 I1=I0+(J-1)*DB%MAXP
 Eta = DB%PrmBuf%D(I1)
 Qx  = DB%PrmBuf%D(I1+1)
 Qy  = DB%PrmBuf%D(I1+2)
 Qz  = DB%PrmBuf%D(I1+3)
 Uq  = DB%PrmBuf%D(I1+4)
 cq1 = DB%PrmBuf%D(I1+5)
 cq2 = DB%PrmBuf%D(I1+6)
 cq3 = DB%PrmBuf%D(I1+7)
 r1xE  = 1.0D0/Eta
 r1x2E = 0.5D0*r1xE
 EtaQx = Eta*Qx
 EtaQy = Eta*Qy
 EtaQz = Eta*Qz
 QBx = Qx-DB%DisBuf%D(I2+7)
 QBy = Qy-DB%DisBuf%D(I2+8)
 QBz = Qz-DB%DisBuf%D(I2+9)
 DO K=1,CBra
 Zeta = PrmBufB(1,K)
 Px   = PrmBufB(2,K)
 Py   = PrmBufB(3,K)
 Pz   = PrmBufB(4,K)
 Up   = PrmBufB(5,K)
 cp1  = PrmBufB(6,K)
 cp2  = PrmBufB(7,K)
 cp3  = PrmBufB(8,K)
 ZpE  = Zeta+Eta
 r1xZpE = 1.0D0/ZpE
 r1x2ZE = 0.5D0*r1xZpE
 r1xZ   = 1.0D0/Zeta
 r1x2Z  = 0.5D0*r1xZ
 rpxZ   = Eta*r1xZpE
 rpxE   = Zeta*r1xZpE
 Rkk  = Up*Uq*DSQRT(r1xZpE)
 PAx = Px-Cx
 PAy = Py-Cy
 PAz = Pz-Cz
 Wx  = (Zeta*Px+EtaQx)*r1xZpE
 Wy  = (Zeta*Py+EtaQy)*r1xZpE
 Wz  = (Zeta*Pz+EtaQz)*r1xZpE
 WPx = Wx-Px
 WPy = Wy-Py
 WPz = Wz-Pz
 WQx = Wx - Qx
 WQy = Wy - Qy
 WQz = Wz - Qz
 PQx = Px - Qx
 PQy = Py - Qy
 PQz = Pz - Qz
 T1=(PQx*PQx+PQy*PQy+PQz*PQz)*Zeta*Eta*r1xZpE
 INCLUDE "RGen3.Inc"
 U(1)=R1                                                          
 U(6)=R2                                                          
 U(5)=R3                                                          
 U(2)=R4                                                          
 U(18)=QBx*U(1)+WQx*U(6)                                          
 U(35)=QBy*U(1)+WQy*U(6)                                          
 U(52)=QBz*U(1)+WQz*U(6)                                          
 U(8)=QBx*U(6)+WQx*U(5)                                           
 U(9)=QBy*U(6)+WQy*U(5)                                           
 U(11)=QBz*U(6)+WQz*U(5)                                          
 U(7)=QBx*U(5)+WQx*U(2)                                           
 U(10)=QBy*U(5)+WQy*U(2)                                          
 U(12)=QBz*U(5)+WQz*U(2)                                          
 U(2)=PAx*U(1)+WPx*U(6)                                           
 U(3)=PAy*U(1)+WPy*U(6)                                           
 U(4)=PAz*U(1)+WPz*U(6)                                           
 U(13)=PAx*U(6)+WPx*U(5)                                          
 U(14)=PAy*U(6)+WPy*U(5)                                          
 U(15)=PAz*U(6)+WPz*U(5)                                          
 U(19)=PAx*U(18)+WPx*U(8)+r1x2ZE*U(6)                                                      
 U(20)=PAy*U(18)+WPy*U(8)                                         
 U(21)=PAz*U(18)+WPz*U(8)                                         
 U(36)=PAx*U(35)+WPx*U(9)                                         
 U(37)=PAy*U(35)+WPy*U(9)+r1x2ZE*U(6)                                                      
 U(38)=PAz*U(35)+WPz*U(9)                                         
 U(53)=PAx*U(52)+WPx*U(11)                                        
 U(54)=PAy*U(52)+WPy*U(11)                                        
 U(55)=PAz*U(52)+WPz*U(11)+r1x2ZE*U(6)                                                     
 U(16)=PAx*U(8)+WPx*U(7)+r1x2ZE*U(5)                                                       
 U(17)=PAy*U(8)+WPy*U(7)                                          
 U(26)=PAz*U(8)+WPz*U(7)                                          
 U(28)=PAx*U(9)+WPx*U(10)                                         
 U(29)=PAy*U(9)+WPy*U(10)+r1x2ZE*U(5)                                                      
 U(30)=PAz*U(9)+WPz*U(10)                                         
 U(31)=PAx*U(11)+WPx*U(12)                                        
 U(32)=PAy*U(11)+WPy*U(12)                                        
 U(33)=PAz*U(11)+WPz*U(12)+r1x2ZE*U(5)                                                     
 U(22)=PAx*U(19)+WPx*U(16)+r1x2Z*(U(18)-rpxZ*U(8))+r1x2ZE*U(13)                            
 U(23)=PAx*U(20)+WPx*U(17)+r1x2ZE*U(14)                                                    
 U(25)=PAx*U(21)+WPx*U(26)+r1x2ZE*U(15)                                                    
 U(41)=PAy*U(37)+WPy*U(29)+r1x2Z*(U(35)-rpxZ*U(9))+r1x2ZE*U(14)                            
 U(43)=PAy*U(38)+WPy*U(30)+r1x2ZE*U(15)                                                    
 U(61)=PAz*U(55)+WPz*U(33)+r1x2Z*(U(52)-rpxZ*U(11))+r1x2ZE*U(15)                           
 U(5)=PAx*U(2)+WPx*U(13)+r1x2Z*(U(1)-rpxZ*U(6))                                            
 U(7)=PAy*U(3)+WPy*U(14)+r1x2Z*(U(1)-rpxZ*U(6))                                            
 U(10)=PAz*U(4)+WPz*U(15)+r1x2Z*(U(1)-rpxZ*U(6))                                           
 U(24)=PAy*U(20)+WPy*U(17)+r1x2Z*(U(18)-rpxZ*U(8))                                         
 U(27)=PAz*U(21)+WPz*U(26)+r1x2Z*(U(18)-rpxZ*U(8))                                         
 U(39)=PAx*U(36)+WPx*U(28)+r1x2Z*(U(35)-rpxZ*U(9))                                         
 U(44)=PAz*U(38)+WPz*U(30)+r1x2Z*(U(35)-rpxZ*U(9))                                         
 U(56)=PAx*U(53)+WPx*U(31)+r1x2Z*(U(52)-rpxZ*U(11))                                        
 U(58)=PAy*U(54)+WPy*U(32)+r1x2Z*(U(52)-rpxZ*U(11))                                        
 U(6)=PAx*U(3)+WPx*U(14)                                          
 U(8)=PAx*U(4)+WPx*U(15)                                          
 U(9)=PAy*U(4)+WPy*U(15)                                          
 U(26)=PAy*U(21)+WPy*U(26)                                        
 U(40)=PAx*U(37)+WPx*U(29)                                        
 U(42)=PAx*U(38)+WPx*U(30)                                        
 U(57)=PAx*U(54)+WPx*U(32)                                        
 U(59)=PAx*U(55)+WPx*U(33)                                        
 U(60)=PAy*U(55)+WPy*U(33)                                        
 C(I,1)=C(I,1)+U(2)*cp2*cq1                                       
 C(I,2)=C(I,2)+U(2)*cq1                                           
 C(I,3)=C(I,3)+U(3)*cq1                                           
 C(I,4)=C(I,4)+U(4)*cq1                                           
 C(I,5)=C(I,5)+U(3)*cp2*cq1                                       
 C(I,6)=C(I,6)+U(5)*cq1                                           
 C(I,7)=C(I,7)+U(6)*cq1                                           
 C(I,8)=C(I,8)+U(7)*cq1                                           
 C(I,9)=C(I,9)+U(4)*cp2*cq1                                       
 C(I,10)=C(I,10)+U(8)*cq1                                         
 C(I,11)=C(I,11)+U(9)*cq1                                         
 C(I,12)=C(I,12)+U(10)*cq1                                        
 C(I,18)=C(I,18)+U(19)*cp2                                        
 C(I,19)=C(I,19)+U(19)                                            
 C(I,20)=C(I,20)+U(20)                                            
 C(I,21)=C(I,21)+U(21)                                            
 C(I,22)=C(I,22)+U(20)*cp2                                        
 C(I,23)=C(I,23)+U(22)                                            
 C(I,24)=C(I,24)+U(23)                                            
 C(I,25)=C(I,25)+U(24)                                            
 C(I,26)=C(I,26)+U(21)*cp2                                        
 C(I,27)=C(I,27)+U(25)                                            
 C(I,28)=C(I,28)+U(26)                                            
 C(I,29)=C(I,29)+U(27)                                            
 C(I,35)=C(I,35)+U(36)*cp2                                        
 C(I,36)=C(I,36)+U(36)                                            
 C(I,37)=C(I,37)+U(37)                                            
 C(I,38)=C(I,38)+U(38)                                            
 C(I,39)=C(I,39)+U(37)*cp2                                        
 C(I,40)=C(I,40)+U(39)                                            
 C(I,41)=C(I,41)+U(40)                                            
 C(I,42)=C(I,42)+U(41)                                            
 C(I,43)=C(I,43)+U(38)*cp2                                        
 C(I,44)=C(I,44)+U(42)                                            
 C(I,45)=C(I,45)+U(43)                                            
 C(I,46)=C(I,46)+U(44)                                            
 C(I,52)=C(I,52)+U(53)*cp2                                        
 C(I,53)=C(I,53)+U(53)                                            
 C(I,54)=C(I,54)+U(54)                                            
 C(I,55)=C(I,55)+U(55)                                            
 C(I,56)=C(I,56)+U(54)*cp2                                        
 C(I,57)=C(I,57)+U(56)                                            
 C(I,58)=C(I,58)+U(57)                                            
 C(I,59)=C(I,59)+U(58)                                            
 C(I,60)=C(I,60)+U(55)*cp2                                        
 C(I,61)=C(I,61)+U(59)                                            
 C(I,62)=C(I,62)+U(60)                                            
 C(I,63)=C(I,63)+U(61)                                            
 ENDDO
 ENDDO
 ENDDO
 ELSEIF(IntCode.EQ. 3020301) THEN
 DO I=1,N
 I0 = SB%SLPrm%I(I)
 I2 = SB%SLDis%I(I)-4
 DO J=1,CKet
 I1=I0+(J-1)*DB%MAXP
 Eta = DB%PrmBuf%D(I1)
 Qx  = DB%PrmBuf%D(I1+1)
 Qy  = DB%PrmBuf%D(I1+2)
 Qz  = DB%PrmBuf%D(I1+3)
 Uq  = DB%PrmBuf%D(I1+4)
 cq1 = DB%PrmBuf%D(I1+5)
 cq2 = DB%PrmBuf%D(I1+6)
 cq3 = DB%PrmBuf%D(I1+7)
 r1xE  = 1.0D0/Eta
 r1x2E = 0.5D0*r1xE
 EtaQx = Eta*Qx
 EtaQy = Eta*Qy
 EtaQz = Eta*Qz
 QBx = Qx-DB%DisBuf%D(I2+7)
 QBy = Qy-DB%DisBuf%D(I2+8)
 QBz = Qz-DB%DisBuf%D(I2+9)
 DO K=1,CBra
 Zeta = PrmBufB(1,K)
 Px   = PrmBufB(2,K)
 Py   = PrmBufB(3,K)
 Pz   = PrmBufB(4,K)
 Up   = PrmBufB(5,K)
 cp1  = PrmBufB(6,K)
 cp2  = PrmBufB(7,K)
 cp3  = PrmBufB(8,K)
 ZpE  = Zeta+Eta
 r1xZpE = 1.0D0/ZpE
 r1x2ZE = 0.5D0*r1xZpE
 r1xZ   = 1.0D0/Zeta
 r1x2Z  = 0.5D0*r1xZ
 rpxZ   = Eta*r1xZpE
 rpxE   = Zeta*r1xZpE
 Rkk  = Up*Uq*DSQRT(r1xZpE)
 PAx = Px-Cx
 PAy = Py-Cy
 PAz = Pz-Cz
 Wx  = (Zeta*Px+EtaQx)*r1xZpE
 Wy  = (Zeta*Py+EtaQy)*r1xZpE
 Wz  = (Zeta*Pz+EtaQz)*r1xZpE
 WPx = Wx-Px
 WPy = Wy-Py
 WPz = Wz-Pz
 WQx = Wx - Qx
 WQy = Wy - Qy
 WQz = Wz - Qz
 PQx = Px - Qx
 PQy = Py - Qy
 PQz = Pz - Qz
 T1=(PQx*PQx+PQy*PQy+PQz*PQz)*Zeta*Eta*r1xZpE
 INCLUDE "RGen3.Inc"
 U(1)=R1                                                          
 U(6)=R2                                                          
 U(5)=R3                                                          
 U(2)=R4                                                          
 U(18)=QBx*U(1)+WQx*U(6)                                          
 U(35)=QBy*U(1)+WQy*U(6)                                          
 U(52)=QBz*U(1)+WQz*U(6)                                          
 U(8)=QBx*U(6)+WQx*U(5)                                           
 U(9)=QBy*U(6)+WQy*U(5)                                           
 U(11)=QBz*U(6)+WQz*U(5)                                          
 U(7)=QBx*U(5)+WQx*U(2)                                           
 U(10)=QBy*U(5)+WQy*U(2)                                          
 U(12)=QBz*U(5)+WQz*U(2)                                          
 U(2)=PAx*U(1)+WPx*U(6)                                           
 U(3)=PAy*U(1)+WPy*U(6)                                           
 U(4)=PAz*U(1)+WPz*U(6)                                           
 U(13)=PAx*U(6)+WPx*U(5)                                          
 U(14)=PAy*U(6)+WPy*U(5)                                          
 U(15)=PAz*U(6)+WPz*U(5)                                          
 U(19)=PAx*U(18)+WPx*U(8)+r1x2ZE*U(6)                                                      
 U(20)=PAy*U(18)+WPy*U(8)                                         
 U(21)=PAz*U(18)+WPz*U(8)                                         
 U(36)=PAx*U(35)+WPx*U(9)                                         
 U(37)=PAy*U(35)+WPy*U(9)+r1x2ZE*U(6)                                                      
 U(38)=PAz*U(35)+WPz*U(9)                                         
 U(53)=PAx*U(52)+WPx*U(11)                                        
 U(54)=PAy*U(52)+WPy*U(11)                                        
 U(55)=PAz*U(52)+WPz*U(11)+r1x2ZE*U(6)                                                     
 U(16)=PAx*U(8)+WPx*U(7)+r1x2ZE*U(5)                                                       
 U(17)=PAy*U(8)+WPy*U(7)                                          
 U(26)=PAz*U(8)+WPz*U(7)                                          
 U(28)=PAx*U(9)+WPx*U(10)                                         
 U(29)=PAy*U(9)+WPy*U(10)+r1x2ZE*U(5)                                                      
 U(30)=PAz*U(9)+WPz*U(10)                                         
 U(31)=PAx*U(11)+WPx*U(12)                                        
 U(32)=PAy*U(11)+WPy*U(12)                                        
 U(33)=PAz*U(11)+WPz*U(12)+r1x2ZE*U(5)                                                     
 U(22)=PAx*U(19)+WPx*U(16)+r1x2Z*(U(18)-rpxZ*U(8))+r1x2ZE*U(13)                            
 U(23)=PAx*U(20)+WPx*U(17)+r1x2ZE*U(14)                                                    
 U(25)=PAx*U(21)+WPx*U(26)+r1x2ZE*U(15)                                                    
 U(41)=PAy*U(37)+WPy*U(29)+r1x2Z*(U(35)-rpxZ*U(9))+r1x2ZE*U(14)                            
 U(43)=PAy*U(38)+WPy*U(30)+r1x2ZE*U(15)                                                    
 U(61)=PAz*U(55)+WPz*U(33)+r1x2Z*(U(52)-rpxZ*U(11))+r1x2ZE*U(15)                           
 U(5)=PAx*U(2)+WPx*U(13)+r1x2Z*(U(1)-rpxZ*U(6))                                            
 U(7)=PAy*U(3)+WPy*U(14)+r1x2Z*(U(1)-rpxZ*U(6))                                            
 U(10)=PAz*U(4)+WPz*U(15)+r1x2Z*(U(1)-rpxZ*U(6))                                           
 U(24)=PAy*U(20)+WPy*U(17)+r1x2Z*(U(18)-rpxZ*U(8))                                         
 U(27)=PAz*U(21)+WPz*U(26)+r1x2Z*(U(18)-rpxZ*U(8))                                         
 U(39)=PAx*U(36)+WPx*U(28)+r1x2Z*(U(35)-rpxZ*U(9))                                         
 U(44)=PAz*U(38)+WPz*U(30)+r1x2Z*(U(35)-rpxZ*U(9))                                         
 U(56)=PAx*U(53)+WPx*U(31)+r1x2Z*(U(52)-rpxZ*U(11))                                        
 U(58)=PAy*U(54)+WPy*U(32)+r1x2Z*(U(52)-rpxZ*U(11))                                        
 U(6)=PAx*U(3)+WPx*U(14)                                          
 U(8)=PAx*U(4)+WPx*U(15)                                          
 U(9)=PAy*U(4)+WPy*U(15)                                          
 U(26)=PAy*U(21)+WPy*U(26)                                        
 U(40)=PAx*U(37)+WPx*U(29)                                        
 U(42)=PAx*U(38)+WPx*U(30)                                        
 U(57)=PAx*U(54)+WPx*U(32)                                        
 U(59)=PAx*U(55)+WPx*U(33)                                        
 U(60)=PAy*U(55)+WPy*U(33)                                        
 C(I,1)=C(I,1)+U(19)*cp2                                          
 C(I,2)=C(I,2)+U(19)                                              
 C(I,3)=C(I,3)+U(20)                                              
 C(I,4)=C(I,4)+U(21)                                              
 C(I,5)=C(I,5)+U(20)*cp2                                          
 C(I,6)=C(I,6)+U(22)                                              
 C(I,7)=C(I,7)+U(23)                                              
 C(I,8)=C(I,8)+U(24)                                              
 C(I,9)=C(I,9)+U(21)*cp2                                          
 C(I,10)=C(I,10)+U(25)                                            
 C(I,11)=C(I,11)+U(26)                                            
 C(I,12)=C(I,12)+U(27)                                            
 C(I,18)=C(I,18)+U(36)*cp2                                        
 C(I,19)=C(I,19)+U(36)                                            
 C(I,20)=C(I,20)+U(37)                                            
 C(I,21)=C(I,21)+U(38)                                            
 C(I,22)=C(I,22)+U(37)*cp2                                        
 C(I,23)=C(I,23)+U(39)                                            
 C(I,24)=C(I,24)+U(40)                                            
 C(I,25)=C(I,25)+U(41)                                            
 C(I,26)=C(I,26)+U(38)*cp2                                        
 C(I,27)=C(I,27)+U(42)                                            
 C(I,28)=C(I,28)+U(43)                                            
 C(I,29)=C(I,29)+U(44)                                            
 C(I,35)=C(I,35)+U(53)*cp2                                        
 C(I,36)=C(I,36)+U(53)                                            
 C(I,37)=C(I,37)+U(54)                                            
 C(I,38)=C(I,38)+U(55)                                            
 C(I,39)=C(I,39)+U(54)*cp2                                        
 C(I,40)=C(I,40)+U(56)                                            
 C(I,41)=C(I,41)+U(57)                                            
 C(I,42)=C(I,42)+U(58)                                            
 C(I,43)=C(I,43)+U(55)*cp2                                        
 C(I,44)=C(I,44)+U(59)                                            
 C(I,45)=C(I,45)+U(60)                                            
 C(I,46)=C(I,46)+U(61)                                            
 ENDDO
 ENDDO
 ENDDO
 ELSEIF(IntCode.EQ. 3030201) THEN
 DO I=1,N
 I0 = SB%SLPrm%I(I)
 I2 = SB%SLDis%I(I)-4
 DO J=1,CKet
 I1=I0+(J-1)*DB%MAXP
 Eta = DB%PrmBuf%D(I1)
 Qx  = DB%PrmBuf%D(I1+1)
 Qy  = DB%PrmBuf%D(I1+2)
 Qz  = DB%PrmBuf%D(I1+3)
 Uq  = DB%PrmBuf%D(I1+4)
 cq1 = DB%PrmBuf%D(I1+5)
 cq2 = DB%PrmBuf%D(I1+6)
 cq3 = DB%PrmBuf%D(I1+7)
 r1xE  = 1.0D0/Eta
 r1x2E = 0.5D0*r1xE
 EtaQx = Eta*Qx
 EtaQy = Eta*Qy
 EtaQz = Eta*Qz
 QBx = Qx-DB%DisBuf%D(I2+7)
 QBy = Qy-DB%DisBuf%D(I2+8)
 QBz = Qz-DB%DisBuf%D(I2+9)
 DO K=1,CBra
 Zeta = PrmBufB(1,K)
 Px   = PrmBufB(2,K)
 Py   = PrmBufB(3,K)
 Pz   = PrmBufB(4,K)
 Up   = PrmBufB(5,K)
 cp1  = PrmBufB(6,K)
 cp2  = PrmBufB(7,K)
 cp3  = PrmBufB(8,K)
 ZpE  = Zeta+Eta
 r1xZpE = 1.0D0/ZpE
 r1x2ZE = 0.5D0*r1xZpE
 r1xZ   = 1.0D0/Zeta
 r1x2Z  = 0.5D0*r1xZ
 rpxZ   = Eta*r1xZpE
 rpxE   = Zeta*r1xZpE
 Rkk  = Up*Uq*DSQRT(r1xZpE)
 PAx = Px-Cx
 PAy = Py-Cy
 PAz = Pz-Cz
 Wx  = (Zeta*Px+EtaQx)*r1xZpE
 Wy  = (Zeta*Py+EtaQy)*r1xZpE
 Wz  = (Zeta*Pz+EtaQz)*r1xZpE
 WPx = Wx-Px
 WPy = Wy-Py
 WPz = Wz-Pz
 WQx = Wx - Qx
 WQy = Wy - Qy
 WQz = Wz - Qz
 PQx = Px - Qx
 PQy = Py - Qy
 PQz = Pz - Qz
 T1=(PQx*PQx+PQy*PQy+PQz*PQz)*Zeta*Eta*r1xZpE
 INCLUDE "RGen3.Inc"
 U(1)=R1                                                          
 U(6)=R2                                                          
 U(5)=R3                                                          
 U(2)=R4                                                          
 U(18)=QBx*U(1)+WQx*U(6)                                          
 U(35)=QBy*U(1)+WQy*U(6)                                          
 U(52)=QBz*U(1)+WQz*U(6)                                          
 U(8)=QBx*U(6)+WQx*U(5)                                           
 U(9)=QBy*U(6)+WQy*U(5)                                           
 U(11)=QBz*U(6)+WQz*U(5)                                          
 U(7)=QBx*U(5)+WQx*U(2)                                           
 U(10)=QBy*U(5)+WQy*U(2)                                          
 U(12)=QBz*U(5)+WQz*U(2)                                          
 U(2)=PAx*U(1)+WPx*U(6)                                           
 U(3)=PAy*U(1)+WPy*U(6)                                           
 U(4)=PAz*U(1)+WPz*U(6)                                           
 U(13)=PAx*U(6)+WPx*U(5)                                          
 U(14)=PAy*U(6)+WPy*U(5)                                          
 U(15)=PAz*U(6)+WPz*U(5)                                          
 U(19)=PAx*U(18)+WPx*U(8)+r1x2ZE*U(6)                                                      
 U(20)=PAy*U(18)+WPy*U(8)                                         
 U(21)=PAz*U(18)+WPz*U(8)                                         
 U(36)=PAx*U(35)+WPx*U(9)                                         
 U(37)=PAy*U(35)+WPy*U(9)+r1x2ZE*U(6)                                                      
 U(38)=PAz*U(35)+WPz*U(9)                                         
 U(53)=PAx*U(52)+WPx*U(11)                                        
 U(54)=PAy*U(52)+WPy*U(11)                                        
 U(55)=PAz*U(52)+WPz*U(11)+r1x2ZE*U(6)                                                     
 U(16)=PAx*U(8)+WPx*U(7)+r1x2ZE*U(5)                                                       
 U(17)=PAy*U(8)+WPy*U(7)                                          
 U(26)=PAz*U(8)+WPz*U(7)                                          
 U(28)=PAx*U(9)+WPx*U(10)                                         
 U(29)=PAy*U(9)+WPy*U(10)+r1x2ZE*U(5)                                                      
 U(30)=PAz*U(9)+WPz*U(10)                                         
 U(31)=PAx*U(11)+WPx*U(12)                                        
 U(32)=PAy*U(11)+WPy*U(12)                                        
 U(33)=PAz*U(11)+WPz*U(12)+r1x2ZE*U(5)                                                     
 U(22)=PAx*U(19)+WPx*U(16)+r1x2Z*(U(18)-rpxZ*U(8))+r1x2ZE*U(13)                            
 U(23)=PAx*U(20)+WPx*U(17)+r1x2ZE*U(14)                                                    
 U(25)=PAx*U(21)+WPx*U(26)+r1x2ZE*U(15)                                                    
 U(41)=PAy*U(37)+WPy*U(29)+r1x2Z*(U(35)-rpxZ*U(9))+r1x2ZE*U(14)                            
 U(43)=PAy*U(38)+WPy*U(30)+r1x2ZE*U(15)                                                    
 U(61)=PAz*U(55)+WPz*U(33)+r1x2Z*(U(52)-rpxZ*U(11))+r1x2ZE*U(15)                           
 U(5)=PAx*U(2)+WPx*U(13)+r1x2Z*(U(1)-rpxZ*U(6))                                            
 U(7)=PAy*U(3)+WPy*U(14)+r1x2Z*(U(1)-rpxZ*U(6))                                            
 U(10)=PAz*U(4)+WPz*U(15)+r1x2Z*(U(1)-rpxZ*U(6))                                           
 U(24)=PAy*U(20)+WPy*U(17)+r1x2Z*(U(18)-rpxZ*U(8))                                         
 U(27)=PAz*U(21)+WPz*U(26)+r1x2Z*(U(18)-rpxZ*U(8))                                         
 U(39)=PAx*U(36)+WPx*U(28)+r1x2Z*(U(35)-rpxZ*U(9))                                         
 U(44)=PAz*U(38)+WPz*U(30)+r1x2Z*(U(35)-rpxZ*U(9))                                         
 U(56)=PAx*U(53)+WPx*U(31)+r1x2Z*(U(52)-rpxZ*U(11))                                        
 U(58)=PAy*U(54)+WPy*U(32)+r1x2Z*(U(52)-rpxZ*U(11))                                        
 U(6)=PAx*U(3)+WPx*U(14)                                          
 U(8)=PAx*U(4)+WPx*U(15)                                          
 U(9)=PAy*U(4)+WPy*U(15)                                          
 U(26)=PAy*U(21)+WPy*U(26)                                        
 U(40)=PAx*U(37)+WPx*U(29)                                        
 U(42)=PAx*U(38)+WPx*U(30)                                        
 U(57)=PAx*U(54)+WPx*U(32)                                        
 U(59)=PAx*U(55)+WPx*U(33)                                        
 U(60)=PAy*U(55)+WPy*U(33)                                        
 C(I,1)=C(I,1)+U(2)*cq1                                           
 C(I,2)=C(I,2)+U(3)*cq1                                           
 C(I,3)=C(I,3)+U(4)*cq1                                           
 C(I,4)=C(I,4)+U(5)*cq1                                           
 C(I,5)=C(I,5)+U(6)*cq1                                           
 C(I,6)=C(I,6)+U(7)*cq1                                           
 C(I,7)=C(I,7)+U(8)*cq1                                           
 C(I,8)=C(I,8)+U(9)*cq1                                           
 C(I,9)=C(I,9)+U(10)*cq1                                          
 C(I,18)=C(I,18)+U(19)                                            
 C(I,19)=C(I,19)+U(20)                                            
 C(I,20)=C(I,20)+U(21)                                            
 C(I,21)=C(I,21)+U(22)                                            
 C(I,22)=C(I,22)+U(23)                                            
 C(I,23)=C(I,23)+U(24)                                            
 C(I,24)=C(I,24)+U(25)                                            
 C(I,25)=C(I,25)+U(26)                                            
 C(I,26)=C(I,26)+U(27)                                            
 C(I,35)=C(I,35)+U(36)                                            
 C(I,36)=C(I,36)+U(37)                                            
 C(I,37)=C(I,37)+U(38)                                            
 C(I,38)=C(I,38)+U(39)                                            
 C(I,39)=C(I,39)+U(40)                                            
 C(I,40)=C(I,40)+U(41)                                            
 C(I,41)=C(I,41)+U(42)                                            
 C(I,42)=C(I,42)+U(43)                                            
 C(I,43)=C(I,43)+U(44)                                            
 C(I,52)=C(I,52)+U(53)                                            
 C(I,53)=C(I,53)+U(54)                                            
 C(I,54)=C(I,54)+U(55)                                            
 C(I,55)=C(I,55)+U(56)                                            
 C(I,56)=C(I,56)+U(57)                                            
 C(I,57)=C(I,57)+U(58)                                            
 C(I,58)=C(I,58)+U(59)                                            
 C(I,59)=C(I,59)+U(60)                                            
 C(I,60)=C(I,60)+U(61)                                            
 ENDDO
 ENDDO
 ENDDO
 ELSEIF(IntCode.EQ. 3030301) THEN
 DO I=1,N
 I0 = SB%SLPrm%I(I)
 I2 = SB%SLDis%I(I)-4
 DO J=1,CKet
 I1=I0+(J-1)*DB%MAXP
 Eta = DB%PrmBuf%D(I1)
 Qx  = DB%PrmBuf%D(I1+1)
 Qy  = DB%PrmBuf%D(I1+2)
 Qz  = DB%PrmBuf%D(I1+3)
 Uq  = DB%PrmBuf%D(I1+4)
 cq1 = DB%PrmBuf%D(I1+5)
 cq2 = DB%PrmBuf%D(I1+6)
 cq3 = DB%PrmBuf%D(I1+7)
 r1xE  = 1.0D0/Eta
 r1x2E = 0.5D0*r1xE
 EtaQx = Eta*Qx
 EtaQy = Eta*Qy
 EtaQz = Eta*Qz
 QBx = Qx-DB%DisBuf%D(I2+7)
 QBy = Qy-DB%DisBuf%D(I2+8)
 QBz = Qz-DB%DisBuf%D(I2+9)
 DO K=1,CBra
 Zeta = PrmBufB(1,K)
 Px   = PrmBufB(2,K)
 Py   = PrmBufB(3,K)
 Pz   = PrmBufB(4,K)
 Up   = PrmBufB(5,K)
 cp1  = PrmBufB(6,K)
 cp2  = PrmBufB(7,K)
 cp3  = PrmBufB(8,K)
 ZpE  = Zeta+Eta
 r1xZpE = 1.0D0/ZpE
 r1x2ZE = 0.5D0*r1xZpE
 r1xZ   = 1.0D0/Zeta
 r1x2Z  = 0.5D0*r1xZ
 rpxZ   = Eta*r1xZpE
 rpxE   = Zeta*r1xZpE
 Rkk  = Up*Uq*DSQRT(r1xZpE)
 PAx = Px-Cx
 PAy = Py-Cy
 PAz = Pz-Cz
 Wx  = (Zeta*Px+EtaQx)*r1xZpE
 Wy  = (Zeta*Py+EtaQy)*r1xZpE
 Wz  = (Zeta*Pz+EtaQz)*r1xZpE
 WPx = Wx-Px
 WPy = Wy-Py
 WPz = Wz-Pz
 WQx = Wx - Qx
 WQy = Wy - Qy
 WQz = Wz - Qz
 PQx = Px - Qx
 PQy = Py - Qy
 PQz = Pz - Qz
 T1=(PQx*PQx+PQy*PQy+PQz*PQz)*Zeta*Eta*r1xZpE
 INCLUDE "RGen3.Inc"
 U(1)=R1                                                          
 U(6)=R2                                                          
 U(5)=R3                                                          
 U(2)=R4                                                          
 U(18)=QBx*U(1)+WQx*U(6)                                          
 U(35)=QBy*U(1)+WQy*U(6)                                          
 U(52)=QBz*U(1)+WQz*U(6)                                          
 U(8)=QBx*U(6)+WQx*U(5)                                           
 U(9)=QBy*U(6)+WQy*U(5)                                           
 U(11)=QBz*U(6)+WQz*U(5)                                          
 U(7)=QBx*U(5)+WQx*U(2)                                           
 U(10)=QBy*U(5)+WQy*U(2)                                          
 U(12)=QBz*U(5)+WQz*U(2)                                          
 U(2)=PAx*U(1)+WPx*U(6)                                           
 U(3)=PAy*U(1)+WPy*U(6)                                           
 U(4)=PAz*U(1)+WPz*U(6)                                           
 U(13)=PAx*U(6)+WPx*U(5)                                          
 U(14)=PAy*U(6)+WPy*U(5)                                          
 U(15)=PAz*U(6)+WPz*U(5)                                          
 U(19)=PAx*U(18)+WPx*U(8)+r1x2ZE*U(6)                                                      
 U(20)=PAy*U(18)+WPy*U(8)                                         
 U(21)=PAz*U(18)+WPz*U(8)                                         
 U(36)=PAx*U(35)+WPx*U(9)                                         
 U(37)=PAy*U(35)+WPy*U(9)+r1x2ZE*U(6)                                                      
 U(38)=PAz*U(35)+WPz*U(9)                                         
 U(53)=PAx*U(52)+WPx*U(11)                                        
 U(54)=PAy*U(52)+WPy*U(11)                                        
 U(55)=PAz*U(52)+WPz*U(11)+r1x2ZE*U(6)                                                     
 U(16)=PAx*U(8)+WPx*U(7)+r1x2ZE*U(5)                                                       
 U(17)=PAy*U(8)+WPy*U(7)                                          
 U(26)=PAz*U(8)+WPz*U(7)                                          
 U(28)=PAx*U(9)+WPx*U(10)                                         
 U(29)=PAy*U(9)+WPy*U(10)+r1x2ZE*U(5)                                                      
 U(30)=PAz*U(9)+WPz*U(10)                                         
 U(31)=PAx*U(11)+WPx*U(12)                                        
 U(32)=PAy*U(11)+WPy*U(12)                                        
 U(33)=PAz*U(11)+WPz*U(12)+r1x2ZE*U(5)                                                     
 U(22)=PAx*U(19)+WPx*U(16)+r1x2Z*(U(18)-rpxZ*U(8))+r1x2ZE*U(13)                            
 U(23)=PAx*U(20)+WPx*U(17)+r1x2ZE*U(14)                                                    
 U(25)=PAx*U(21)+WPx*U(26)+r1x2ZE*U(15)                                                    
 U(41)=PAy*U(37)+WPy*U(29)+r1x2Z*(U(35)-rpxZ*U(9))+r1x2ZE*U(14)                            
 U(43)=PAy*U(38)+WPy*U(30)+r1x2ZE*U(15)                                                    
 U(61)=PAz*U(55)+WPz*U(33)+r1x2Z*(U(52)-rpxZ*U(11))+r1x2ZE*U(15)                           
 U(5)=PAx*U(2)+WPx*U(13)+r1x2Z*(U(1)-rpxZ*U(6))                                            
 U(7)=PAy*U(3)+WPy*U(14)+r1x2Z*(U(1)-rpxZ*U(6))                                            
 U(10)=PAz*U(4)+WPz*U(15)+r1x2Z*(U(1)-rpxZ*U(6))                                           
 U(24)=PAy*U(20)+WPy*U(17)+r1x2Z*(U(18)-rpxZ*U(8))                                         
 U(27)=PAz*U(21)+WPz*U(26)+r1x2Z*(U(18)-rpxZ*U(8))                                         
 U(39)=PAx*U(36)+WPx*U(28)+r1x2Z*(U(35)-rpxZ*U(9))                                         
 U(44)=PAz*U(38)+WPz*U(30)+r1x2Z*(U(35)-rpxZ*U(9))                                         
 U(56)=PAx*U(53)+WPx*U(31)+r1x2Z*(U(52)-rpxZ*U(11))                                        
 U(58)=PAy*U(54)+WPy*U(32)+r1x2Z*(U(52)-rpxZ*U(11))                                        
 U(6)=PAx*U(3)+WPx*U(14)                                          
 U(8)=PAx*U(4)+WPx*U(15)                                          
 U(9)=PAy*U(4)+WPy*U(15)                                          
 U(26)=PAy*U(21)+WPy*U(26)                                        
 U(40)=PAx*U(37)+WPx*U(29)                                        
 U(42)=PAx*U(38)+WPx*U(30)                                        
 U(57)=PAx*U(54)+WPx*U(32)                                        
 U(59)=PAx*U(55)+WPx*U(33)                                        
 U(60)=PAy*U(55)+WPy*U(33)                                        
 C(I,1)=C(I,1)+U(19)                                              
 C(I,2)=C(I,2)+U(20)                                              
 C(I,3)=C(I,3)+U(21)                                              
 C(I,4)=C(I,4)+U(22)                                              
 C(I,5)=C(I,5)+U(23)                                              
 C(I,6)=C(I,6)+U(24)                                              
 C(I,7)=C(I,7)+U(25)                                              
 C(I,8)=C(I,8)+U(26)                                              
 C(I,9)=C(I,9)+U(27)                                              
 C(I,18)=C(I,18)+U(36)                                            
 C(I,19)=C(I,19)+U(37)                                            
 C(I,20)=C(I,20)+U(38)                                            
 C(I,21)=C(I,21)+U(39)                                            
 C(I,22)=C(I,22)+U(40)                                            
 C(I,23)=C(I,23)+U(41)                                            
 C(I,24)=C(I,24)+U(42)                                            
 C(I,25)=C(I,25)+U(43)                                            
 C(I,26)=C(I,26)+U(44)                                            
 C(I,35)=C(I,35)+U(53)                                            
 C(I,36)=C(I,36)+U(54)                                            
 C(I,37)=C(I,37)+U(55)                                            
 C(I,38)=C(I,38)+U(56)                                            
 C(I,39)=C(I,39)+U(57)                                            
 C(I,40)=C(I,40)+U(58)                                            
 C(I,41)=C(I,41)+U(59)                                            
 C(I,42)=C(I,42)+U(60)                                            
 C(I,43)=C(I,43)+U(61)                                            
 ENDDO
 ENDDO
 ENDDO
 ELSE
  CALL Halt("Illegal IntCode")
 ENDIF
END SUBROUTINE Int2221
