MODULE ParallelKeys
  CHARACTER(LEN=9),  PARAMETER :: MPI_INVOCATION       = 'MPIInvoke'
  CHARACTER(LEN=11), PARAMETER :: MPI_MACHINE_FLAG     = 'MPIMachFlag'
  CHARACTER(LEN=11), PARAMETER :: MPI_PROCESSOR_FLAG   = 'MPIProcFlag'
  CHARACTER(LEN=13), PARAMETER :: MPI_PROCESSOR_NUMBER = 'MPIProcessors'
  CHARACTER(LEN=14), PARAMETER :: MPI_SPATIAL_PROC     = 'MPISpatialProc'
  CHARACTER(LEN=14), PARAMETER :: MPI_MACHINE_FILE     = 'MPIMachineFile'
END MODULE ParallelKeys
