MODULE ParallelKeys
  CHARACTER(LEN=*),  PARAMETER :: MPI_INVOCATION       = 'MPIInvoke'
  CHARACTER(LEN=*), PARAMETER :: MPI_PROCESSOR_FLAG   = 'MPIProcFlag'
  CHARACTER(LEN=*), PARAMETER :: MPI_PROCESSOR_NUMBER = 'MPIProcessors'
  CHARACTER(LEN=*), PARAMETER :: MPI_SPATIAL_PROC     = 'MPISpatialProc'
  CHARACTER(LEN=*), PARAMETER :: MPI_MACHINE_FLAG     = 'MPIMachineFlag'
  CHARACTER(LEN=*), PARAMETER :: MPI_MACHINE_FILE     = 'MPIMachineFile'
END MODULE ParallelKeys
