MODULE PeriodicKeys
   CHARACTER(LEN=*), PARAMETER :: BEGIN_PERIODIC='<BeginPeriodic>'
   CHARACTER(LEN=*), PARAMETER :: END_PERIODIC  ='<EndPeriodic>'
!
   CHARACTER(LEN=*),  PARAMETER :: PBOUNDRY     ='Periodic' 
   CHARACTER(LEN=*),  PARAMETER :: PBCWRAP      ='PBC'
!
   CHARACTER(LEN=10), PARAMETER :: ATOMW_OFF    ='NoAtomWrap'
!
   CHARACTER(LEN=*),  PARAMETER :: ALAT_VEC     ='av'
   CHARACTER(LEN=*),  PARAMETER :: BLAT_VEC     ='bv'
   CHARACTER(LEN=*),  PARAMETER :: CLAT_VEC     ='cv'
!
   CHARACTER(LEN=*),  PARAMETER :: PBC_TRUE     ='T'
   CHARACTER(LEN=*),  PARAMETER :: PBC_FALSE    ='F'
!
   CHARACTER(LEN=*), PARAMETER :: CRT_ATOM     ='AtomCoord'
   CHARACTER(LEN=*), PARAMETER :: CRT_FRAC     ='FracCoord'
!
   CHARACTER(LEN=*), PARAMETER :: PFFMXELL     ='PFFMaxEll'
   CHARACTER(LEN=*), PARAMETER :: PFFMXLAY     ='PFFLayers'
   CHARACTER(LEN=*), PARAMETER :: PFFOVRDE     ='PFFOverRide'
!
   CHARACTER(LEN=7),  PARAMETER :: CENTERATOMS  ='CenterAtoms'
   CHARACTER(LEN=7),  PARAMETER :: EPSILON      ='Epsilon'
!
 END MODULE PeriodicKeys
