MODULE PeriodicKeys
   CHARACTER(LEN=19), PARAMETER :: BEGIN_PERIODIC='<BeginPeriodic>'
   CHARACTER(LEN=17), PARAMETER :: END_PERIODIC  ='<EndPeriodic>'

   CHARACTER(LEN=9),  PARAMETER :: PBOUNDRY     ='Periodic' 
!
   CHARACTER(LEN=3),  PARAMETER :: PBC_OFF      ='Off'
!
   CHARACTER(LEN=8),  PARAMETER :: ATOMW_ON     ='AtomWrap'
   CHARACTER(LEN=10), PARAMETER :: ATOMW_OFF    ='NoAtomWrap'
!
   CHARACTER(LEN=2),  PARAMETER :: TRAN_VEC     ='tv'
   CHARACTER(LEN=2),  PARAMETER :: ALAT_VEC     ='av'
   CHARACTER(LEN=2),  PARAMETER :: BLAT_VEC     ='bv'
   CHARACTER(LEN=2),  PARAMETER :: CLAT_VEC     ='cv'
!
   CHARACTER(LEN=10), PARAMETER :: CRT_ATOM     ='AtomCoord'
   CHARACTER(LEN=10), PARAMETER :: CRT_FRAC     ='FracCoord'
!
   CHARACTER(LEN=10), PARAMETER :: PFFMXELL     ='PFFMaxEll'
   CHARACTER(LEN=10), PARAMETER :: PFFMXLAY     ='PFFLayers'
   CHARACTER(LEN=12), PARAMETER :: PFFOVRDE     ='PFFOverRide'
!
   CHARACTER(LEN=7),  PARAMETER :: EPSILON      ='Epsilon'
 END MODULE PeriodicKeys
