MODULE SCFKeys
  CHARACTER(LEN=*), PARAMETER :: SCF_DENSITY_BUILD    ='DensityBuild'
! 
  CHARACTER(LEN=*), PARAMETER :: SCF_INKFOCK          ='InkFok'
  CHARACTER(LEN=*), PARAMETER :: SCF_RESTART          ='Restart'
  CHARACTER(LEN=*), PARAMETER :: SCF_PROJECTION       ='Project'
  CHARACTER(LEN=*), PARAMETER :: SCF_GUESSEQCORE      ='GuessEqCore'
  CHARACTER(LEN=*), PARAMETER :: SCF_EXTRAPOLATE      ='Extrapolate'
  CHARACTER(LEN=*), PARAMETER :: SCF_SUPERPOSITION    ='DensitySuperposition'
  CHARACTER(LEN=*), PARAMETER :: SCF_DENSITY_NORMAL   ='DensityNormal'
  CHARACTER(LEN=*), PARAMETER :: SCF_BASISSETSWITCH   ='BasisSetSwitch'
  CHARACTER(LEN=*), PARAMETER :: SCF_RWBSS            ='RestartBasisSwitch'
!
  CHARACTER(LEN=*), PARAMETER :: SCF_FOCK_BUILD       ='FockBuild'
  CHARACTER(LEN=*), PARAMETER :: SCF_SOLVE_SCF        ='SCFSolving'
!
  CHARACTER(LEN=*), PARAMETER :: CPSCF_START_RESPONSE ='StartResponse'
  CHARACTER(LEN=*), PARAMETER :: CPSCF_DENSITY_NORMAL ='DensityPrime'
  CHARACTER(LEN=*), PARAMETER :: CPSCF_FOCK_BUILD     ='FockPrimeBuild'
  CHARACTER(LEN=*), PARAMETER :: CPSCF_SOLVE_SCF      ='CPSCFSolving'
END MODULE SCFKeys

