MODULE SCFKeys
  CHARACTER(LEN=12),PARAMETER :: SCF_DENSITY_BUILD    ='DensityBuild'
! 
  CHARACTER(LEN=6), PARAMETER :: SCF_INKFOCK          ='InkFok'
  CHARACTER(LEN=7), PARAMETER :: SCF_RESTART          ='Restart'
  CHARACTER(LEN=7), PARAMETER :: SCF_PROJECTION       ='Project'
  CHARACTER(LEN=11),PARAMETER :: SCF_GUESSEQCORE      ='GuessEqCore'
  CHARACTER(LEN=11),PARAMETER :: SCF_EXTRAPOLATE      ='Extrapolate'
!  CHARACTER(LEN=13),PARAMETER :: SCF_SUPERPOSITION    ='SuperPosition'
  CHARACTER(LEN=20),PARAMETER :: SCF_SUPERPOSITION    ='DensitySuperposition'
  CHARACTER(LEN=13),PARAMETER :: SCF_DENSITY_NORMAL   ='DensityNormal'
  CHARACTER(LEN=14),PARAMETER :: SCF_BASISSETSWITCH   ='BasisSetSwitch'
!
  CHARACTER(LEN=9), PARAMETER :: SCF_FOCK_BUILD       ='FockBuild'
  CHARACTER(LEN=10),PARAMETER :: SCF_SOLVE_SCF        ='SCFSolving'
END MODULE SCFKeys

