MODULE ZippyQuote
  IMPLICIT NONE
CONTAINS
  SUBROUTINE ZippySez(N)
    CHARACTER(LEN=50),DIMENSION(30) :: ZS=(/
    "Are we having fun yet?",
    "I am demographically correct.",
    "I just became one with my browser software.",
    "Virtual reality isn't what it used to be.",
    "I want a mega-meal in a mega-mall.",
    "Adopt my lifestyle or I'll have to press charges.",
    "If you can't say something nice, say something surrealistic.",
    "I'm afraid! I need something in a heavy cream sauce.",
    "I can silence Joan Rivers with a single slice of Kraft cheese.",
    "I am protected by the power of stain-reistant Scotchguard",
    "I just accepted provolone into my life.",
    "Frivolity is a stern taskmaster.",
    "All life is a blur of Republicans and meat.",
    "I'm Zippy the Pinhead and I'm totally committed to the festive mode.",
    "I just felt a paradigm shift.",
    "My boxer shorts just went on a rampage through a Long Island bowling alley.",
    "Glazed donuts are the building blocks of the universe.",
    "Nobody brings small problems into a laundromat.",
    "Consciousness is vastly overrated.",
    "I hope my sensitive female side is wearing sensible leather pumps.",
    "Reality distorts my sense of television.",
    "AIEEEEE!  I am having an UNDULATING EXPERIENCE!",
    "Am I accompanied by a PARENT or GUARDIAN?",
    "Am I in GRADUATE SCHOOL yet?",
    "Are we live or on tape?",
    "As a FAD follower, my BEVERAGE choices are rich and fulfilling!",
    "BELA LUGOSI is my co-pilot..",
    "Can I have an IMPULSE ITEM instead?",
    "Everywhere I look I see NEGATIVITY and ASPHALT...",
    "Half a mind is a terrible thing to waste!",
    "He is the MELBA-BEING...  the ANGEL CAKE... XEROX him...  XEROX him --",
    "Hmmm...  an arrogant bouquet with a subtle suggestion of POLYVINYL CHLORIDE...",
    "I can't decide which WRONG TURN to make first!!",
    "I guess you guys got BIG MUSCLES from doing too much STUDYING!",
    "I had pancake makeup for brunch!",
    "I just heard the SEVENTIES were over!!  And I was just getting in touch with my LEISURE SUIT!!",
    "I think I am an overnight sensation right now!!",
..  "I think I'd better go back to my DESK and toy with a few common MISAPPREHENSIONS...",
    "I used to be a FUNDAMENTALIST, but then I heard about the HIGH RADIATION LEVELS and bought an ENCYCLOPEDIA!!",
    "I will SHAVE and buy JELL-O and bring my MARRIAGE MANUAL!!",
    "Impudent..  Yet possessing a certain ALUMINUM SILICATE overbite....Needs REDDY-WHIP!!",
  END SUBROUTINE ZippySez
END MODULE ZippyQuote
