Document: freeon
Title: Debian freeon Manual
Author: <insert document author here>
Abstract: This manual describes what freeon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/freeon/freeon.sgml.gz

Format: postscript
Files: /usr/share/doc/freeon/freeon.ps.gz

Format: text
Files: /usr/share/doc/freeon/freeon.text.gz

Format: HTML
Index: /usr/share/doc/freeon/html/index.html
Files: /usr/share/doc/freeon/html/*.html
