#!/bin/tcsh
dbx  $MONDO_EXEC/$1  -I$MONDO_HOME/MondoMods   \
                     -I$MONDO_HOME/MondoSCF    \
                     -I$MONDO_HOME/OneE        \
                     -I$MONDO_HOME/QCTC        \
                     -I$MONDO_HOME/HiCu        \
                     -I$MONDO_HOME/ONX/NONX    \
                     -I$MONDO_HOME/QuNew       \
                     -I$MONDO_HOME/SCFeqs      \
                     -I$MONDO_HOME/XForm       \
                     -I$MONDO_HOME/VisDX       \
                  $2
