/*
**
** PHiPAC Matrix-Matrix Code for the operation:
**    C = alpha*A*B + beta*C
**
** Automatically Generated by mm_cgen ($Revision: 1.2 $) using the command:
**    ./mm_cgen -prec double -opA N -opB N -alpha c -ignore_m1 -sp 1 -holdstripe B -l0 4 15 1 -file ./src/mm_double_NN_c.c -routine_name mm_double_NN_c -beta c 
**
** Run './mm_cgen -help' for help.
**
** Generated on: Saturday August 18 2001, 07:05:09 MDT
** Created by: Jeff Bilmes <bilmes@cs.berkeley.edu>
**             http://www.icsi.berkeley.edu/~bilmes/phipac
**
**
** Routine Usage: General (M,K,N) = (M, K, N) matrix multiply
**    mm_double_NN_c(const int M, const int K, const int N, const double *const A, const double *const B, double *const C, const int Astride, const int Bstride, const int Cstride, const double alpha, const double beta)
** where
**  A is an MxK matrix
**  B is an KxN matrix
**  C is an MxN matrix
**  Astride is the number of entries between the start of each row of A
**  Bstride is the number of entries between the start of each row of B
**  Cstride is the number of entries between the start of each row of C
**
**
** "Copyright (c) 1995 The Regents of the University of California.  All
** rights reserved."  Permission to use, copy, modify, and distribute
** this software and its documentation for any purpose, without fee, and
** without written agreement is hereby granted, provided that the above
** copyright notice and the following two paragraphs appear in all copies
** of this software.
**
** IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
** DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
** OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF
** CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
** THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
** INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
** AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
** ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATION TO
** PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
**
*/

/*
 * General (M,K,N) = (M, K, N) matrix multiply
 */

#define NO_MB

void
mm_double_NN_c(const int M, const int K, const int N, const double *const A, const double *const B, double *const C, const int Astride, const int Bstride, const int Cstride, const double alpha, const double beta)
{
   const double *a;
   const double *b;
   double *c;
   const double *ap_0,*ap_1,*ap_2,*ap_3;
   const double *bp;
   double *cp;
   const int A_sbs_stride = Astride*4;
   const int C_sbs_stride = Cstride*4;
   const int k_marg_el = K % 15;
   const int k_norm = K - k_marg_el;
   const int m_marg_el = M & 3;
   const int m_norm = M - m_marg_el;
   const int n_marg_el = N & 0;
   const int n_norm = N - n_marg_el;
   double *const c_endp = C+m_norm*Cstride;
   register double c0_0,c1_0,c2_0,c3_0;
   if (beta == 0.0) {
      double *cprb,*cpre,*cp,*cpe;
      cpre = C + M*Cstride;
      for (cprb = C; cprb != cpre; cprb += Cstride) {
         cpe = cprb + N;
         for (cp = cprb; cp != cpe; cp++) {
            *cp = 0.0;
         }
      }
   } else if (beta != 1.0) {
      double *cprb,*cpre,*cp,*cpe;
      cpre = C + M*Cstride;
      for (cprb = C; cprb != cpre; cprb += Cstride) {
         cpe = cprb + N;
         for (cp = cprb; cp != cpe; cp++) {
            *cp *= (beta);
         }
      }
   }
   for (c=C,a=A; c!= c_endp; c+=C_sbs_stride,a+=A_sbs_stride) {
      const double* const ap_endp = a + k_norm;
      double* const cp_endp = c + n_norm;
      const double* const apc_1 = a + Astride;
      const double* const apc_2 = apc_1 + Astride;
      const double* const apc_3 = apc_2 + Astride;
      for (b=B,cp=c; cp!=cp_endp; b+=1,cp+=1) {
         register double _b0;
         register double _a0,_a1,_a2,_a3;
         double *_cp;
         ap_0 = a;
         ap_1 = apc_1;
         ap_2 = apc_2;
         ap_3 = apc_3;
         bp=b;
         c0_0 = 0.0; 
         c1_0 = 0.0; 
         c2_0 = 0.0; 
         c3_0 = 0.0; 
         for (;ap_0!=ap_endp; ap_0+=15,ap_1+=15,ap_2+=15,ap_3+=15) {
            /* Fixed M,K,N = 4,15,1 fully-unrolled matrix matrix multiply. */
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[0];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[0];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[0];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[0];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[1];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[1];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[1];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[1];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[2];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[2];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[2];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[2];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[3];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[3];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[3];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[3];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[4];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[4];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[4];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[4];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[5];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[5];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[5];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[5];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[6];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[6];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[6];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[6];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[7];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[7];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[7];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[7];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[8];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[8];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[8];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[8];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[9];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[9];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[9];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[9];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[10];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[10];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[10];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[10];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[11];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[11];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[11];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[11];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[12];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[12];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[12];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[12];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[13];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[13];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[13];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[13];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[14];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[14];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[14];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[14];
            c3_0 += _a3*_b0; 

         }
         if (k_marg_el & 0x8) {
            /* Fixed M,K,N = 4,8,1 fully-unrolled matrix matrix multiply. */
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[0];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[0];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[0];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[0];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[1];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[1];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[1];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[1];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[2];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[2];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[2];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[2];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[3];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[3];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[3];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[3];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[4];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[4];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[4];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[4];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[5];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[5];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[5];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[5];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[6];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[6];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[6];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[6];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[7];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[7];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[7];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[7];
            c3_0 += _a3*_b0; 

            ap_0+=8;ap_1+=8;ap_2+=8;ap_3+=8;
         }
         if (k_marg_el & 0x4) {
            /* Fixed M,K,N = 4,4,1 fully-unrolled matrix matrix multiply. */
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[0];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[0];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[0];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[0];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[1];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[1];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[1];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[1];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[2];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[2];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[2];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[2];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[3];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[3];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[3];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[3];
            c3_0 += _a3*_b0; 

            ap_0+=4;ap_1+=4;ap_2+=4;ap_3+=4;
         }
         if (k_marg_el & 0x2) {
            /* Fixed M,K,N = 4,2,1 fully-unrolled matrix matrix multiply. */
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[0];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[0];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[0];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[0];
            c3_0 += _a3*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[1];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[1];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[1];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[1];
            c3_0 += _a3*_b0; 

            ap_0+=2;ap_1+=2;ap_2+=2;ap_3+=2;
         }
         if (k_marg_el & 0x1) {
            /* Fixed M,K,N = 4,1,1 fully-unrolled matrix matrix multiply. */
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[0];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[0];
            c1_0 += _a1*_b0; 
            _a2 = ap_2[0];
            c2_0 += _a2*_b0; 
            _a3 = ap_3[0];
            c3_0 += _a3*_b0; 

         }
         _cp=cp;_cp[0]+=alpha*c0_0;
         _cp+=Cstride;_cp[0]+=alpha*c1_0;
         _cp+=Cstride;_cp[0]+=alpha*c2_0;
         _cp+=Cstride;_cp[0]+=alpha*c3_0;
      }
   }
   if (m_marg_el & 0x2) {
      const double* const ap_endp = a + k_norm;
      double* const cp_endp = c + n_norm;
      const double* const apc_1 = a + Astride;
      for (b=B,cp=c; cp!=cp_endp; b+=1,cp+=1) {
         register double _b0;
         register double _a0,_a1;
         double *_cp;
         ap_0 = a;
         ap_1 = apc_1;
         bp=b;
         c0_0 = 0.0; 
         c1_0 = 0.0; 
         for (;ap_0!=ap_endp; ap_0+=15,ap_1+=15) {
            /* Fixed M,K,N = 2,15,1 fully-unrolled matrix matrix multiply. */
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[0];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[0];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[1];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[1];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[2];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[2];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[3];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[3];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[4];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[4];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[5];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[5];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[6];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[6];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[7];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[7];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[8];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[8];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[9];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[9];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[10];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[10];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[11];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[11];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[12];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[12];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[13];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[13];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[14];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[14];
            c1_0 += _a1*_b0; 

         }
         if (k_marg_el & 0x8) {
            /* Fixed M,K,N = 2,8,1 fully-unrolled matrix matrix multiply. */
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[0];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[0];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[1];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[1];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[2];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[2];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[3];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[3];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[4];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[4];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[5];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[5];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[6];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[6];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[7];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[7];
            c1_0 += _a1*_b0; 

            ap_0+=8;ap_1+=8;
         }
         if (k_marg_el & 0x4) {
            /* Fixed M,K,N = 2,4,1 fully-unrolled matrix matrix multiply. */
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[0];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[0];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[1];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[1];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[2];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[2];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[3];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[3];
            c1_0 += _a1*_b0; 

            ap_0+=4;ap_1+=4;
         }
         if (k_marg_el & 0x2) {
            /* Fixed M,K,N = 2,2,1 fully-unrolled matrix matrix multiply. */
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[0];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[0];
            c1_0 += _a1*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[1];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[1];
            c1_0 += _a1*_b0; 

            ap_0+=2;ap_1+=2;
         }
         if (k_marg_el & 0x1) {
            /* Fixed M,K,N = 2,1,1 fully-unrolled matrix matrix multiply. */
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[0];
            c0_0 += _a0*_b0; 
            _a1 = ap_1[0];
            c1_0 += _a1*_b0; 

         }
         _cp=cp;_cp[0]+=alpha*c0_0;
         _cp+=Cstride;_cp[0]+=alpha*c1_0;
      }
      c += Cstride*2;
      a += Astride*2;
   }
   if (m_marg_el & 0x1) {
      const double* const ap_endp = a + k_norm;
      double* const cp_endp = c + n_norm;
      for (b=B,cp=c; cp!=cp_endp; b+=1,cp+=1) {
         register double _b0;
         register double _a0;
         double *_cp;
         ap_0 = a;
         bp=b;
         c0_0 = 0.0; 
         for (;ap_0!=ap_endp; ap_0+=15) {
            /* Fixed M,K,N = 1,15,1 fully-unrolled matrix matrix multiply. */
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[0];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[1];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[2];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[3];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[4];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[5];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[6];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[7];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[8];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[9];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[10];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[11];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[12];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[13];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[14];
            c0_0 += _a0*_b0; 

         }
         if (k_marg_el & 0x8) {
            /* Fixed M,K,N = 1,8,1 fully-unrolled matrix matrix multiply. */
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[0];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[1];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[2];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[3];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[4];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[5];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[6];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[7];
            c0_0 += _a0*_b0; 

            ap_0+=8;
         }
         if (k_marg_el & 0x4) {
            /* Fixed M,K,N = 1,4,1 fully-unrolled matrix matrix multiply. */
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[0];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[1];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[2];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[3];
            c0_0 += _a0*_b0; 

            ap_0+=4;
         }
         if (k_marg_el & 0x2) {
            /* Fixed M,K,N = 1,2,1 fully-unrolled matrix matrix multiply. */
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[0];
            c0_0 += _a0*_b0; 
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[1];
            c0_0 += _a0*_b0; 

            ap_0+=2;
         }
         if (k_marg_el & 0x1) {
            /* Fixed M,K,N = 1,1,1 fully-unrolled matrix matrix multiply. */
            
            _b0 = bp[0]; 
            bp += Bstride;
            _a0 = ap_0[0];
            c0_0 += _a0*_b0; 

         }
         _cp=cp;_cp[0]+=alpha*c0_0;
      }
   }
}
