c       ------------------------------ 
        CTwo2=-(Cpq2*CBufK(0,KK,J))
        STwo2=-(Spq2*CBufK(0,KK,J))
        CTwo4=Cpq4*CBufK(0,KK,J)
        STwo4=Spq4*CBufK(0,KK,J)
        CTwo5=Cpq5*CBufK(0,KK,J)
        STwo5=Spq5*CBufK(0,KK,J)
        CTwo7=-(Cpq7*CBufK(0,KK,J))
        STwo7=-(Spq7*CBufK(0,KK,J))
        CTwo8=-(Cpq8*CBufK(0,KK,J))
        STwo8=-(Spq8*CBufK(0,KK,J))
        CTwo9=-(Cpq9*CBufK(0,KK,J))
        STwo9=-(Spq9*CBufK(0,KK,J))
c       ------------------------------ 
        Cone0=Cpq0*CBufK(0,KK,J)
        Cone1=-(Cpq1*CBufK(0,KK,J))
        Cone3=Cpq3*CBufK(0,KK,J)
        Cone6=-(Cpq6*CBufK(0,KK,J))
c       ------------------------------ 
        CKet(0)=COne0
        SKet(0)=Zero
        CKet(1)=COne1
        SKet(1)=Zero
        CKet(2)=2.D0*CTwo2
        SKet(2)=2.D0*STwo2
        CKet(3)=COne3
        SKet(3)=Zero
        CKet(4)=2.D0*CTwo4
        SKet(4)=2.D0*STwo4
        CKet(5)=2.D0*CTwo5
        SKet(5)=2.D0*STwo5
        CKet(6)=COne6
        SKet(6)=Zero
        CKet(7)=2.D0*CTwo7
        SKet(7)=2.D0*STwo7
        CKet(8)=2.D0*CTwo8
        SKet(8)=2.D0*STwo8
        CKet(9)=2.D0*CTwo9
        SKet(9)=2.D0*STwo9
c       ------------------------------ 
         
